kind: Service
apiVersion: v1
metadata:
  name: pw-mongodb-replicaset-0
  namespace: ntc
spec:
  type: ExternalName
  externalName: pw-mongodb-replicaset-0.stores.svc.cluster.local
  ports:
  - port: 27017

--- 

kind: Service
apiVersion: v1
metadata:
  name: pw-mongodb-replicaset-1
  namespace: ntc
spec:
  type: ExternalName
  externalName: pw-mongodb-replicaset-1.stores.svc.cluster.local
  ports:
  - port: 27017

--- 

kind: Service
apiVersion: v1
metadata:
  name: pw-mongodb-replicaset-2
  namespace: ntc
spec:
  type: ExternalName
  externalName: pw-mongodb-replicaset-2.stores.svc.cluster.local
  ports:
  - port: 27017
