apiVersion: v1
kind: Service
metadata:
  name: bitcoin-core
spec:
  selector:
    app: bitcoin-core
  ports:
    - protocol: TCP
      port: 18443
      targetPort: 18443
    - protocol: TCP
      port: 18444
      targetPort: 18444
    - protocol: TCP
      port: 18332
      targetPort: 18332
    - protocol: TCP
      port: 18333
      targetPort: 18333
    - protocol: TCP
      port: 8332
      targetPort: 8332
    - protocol: TCP
      port: 8333
      targetPort: 8333