apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntc-services
#  namespace: ntc
spec:
  selector:
    matchLabels:
      app: ntc-services
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ntc-services
    spec:
      containers:
        - name: ntc-services
          image: gcr.io/pineappleworkshop/ntc-services:0.0.5
          env:
            - name: ENV
              value: 'dev'
