apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntc-services
spec:
  selector:
    matchLabels:
      app: ntc-services
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ntc-services
    spec:
      containers:
        - name: ntc-services
          image: gcr.io/pineappleworkshop/ntc-services:0.0.56
          env:
            - name: ENV
              value: 'dev'
          volumeMounts:
            - name: state
              mountPath: /state
      volumes:
        - name: state
          emptyDir: {}