apiVersion: v1
kind: Service
metadata:
  labels:
    app: omnisat-api
  name: omnisat-api
  namespace: omnisat
spec:
  type: LoadBalancer
  ports:
    - port: 3444
      targetPort: 3444
      protocol: TCP
  selector:
    app: omnisat-api
