apiVersion: v1
kind: Service
metadata:
  labels:
    app: ntc-services
  name: ntc-services
  namespace: ntc
spec:
  type: LoadBalancer
  ports:
    - port: 3444
      targetPort: 3444
      protocol: TCP
  selector:
    app: ntc-services
