apiVersion: v1
kind: Service
metadata:
  name: ntc-services
spec:
  selector:
    app: ntc-services
  ports:
    - protocol: TCP
      port: 3444

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntc-services
spec:
  replicas: 9
  serviceName: "ntc-services"
  selector:
    matchLabels:
      app: ntc-services
  template:
    metadata:
      labels:
        app: ntc-services
    spec:
      containers:
        - name: ntc-services
          image: gcr.io/pineappleworkshop/ntc-services:0.0.39
          env:
            - name: ENV
              value: 'dev'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: state
              mountPath: /state
      volumes:
        - name: state
          emptyDir: {}
