apiVersion: v1
kind: Service
metadata:
  name: ntc-scanner
spec:
  selector:
    app: ntc-scanner
  ports:
    - protocol: TCP
      port: 3444

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ntc-scanner
spec:
  replicas: 9
  serviceName: "ntc-scanner"
  selector:
    matchLabels:
      app: ntc-scanner
  template:
    metadata:
      labels:
        app: ntc-scanner
    spec:
      containers:
        - name: ntc-scanner
          image: gcr.io/pineappleworkshop/ntc-services:0.0.39
          env:
            - name: ENV
              value: 'dev'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: state
              mountPath: /state
      volumes:
        - name: state
          emptyDir: {}
